
openapi: "3.0.0"
info:
  title: Expense Tracker API
  version: 1.0.0
  description: Full API documentation for Expense Tracker backend.
servers:
  - url: http://localhost:4000/api/v1
    description: Local server

components:
  securitySchemes: 
    bearerAuth: 
      type: "http"
      scheme: "bearer"
      bearerFormat: "JWT"
      
security: 
  - bearerAuth: []
      
    
tags:
  - name: Auth
    description: Authentication and authorization endpoints.
  - name: OAuth
    description: Third Party Authentication and authorization endpoints.
  - name: User
    description: User management endpoints.
  - name: Expense
    description: Expense Management endpoints.
  - name: Category
    description: Category management endpoints.
  - name: Admin
    description: Administrative endpoints for managing users, expenses & categories.
  - name: Subscription
    description: Endpoints for creating Stripe Checkout sessions, managing user subscriptions, and handling billing webhooks for the Expenses Tracker Pro plan.
  - name: Metrics
    description: Endpoints for exposing metrics for prometheus
